### ISSUE TITLE
Title of Nurse position on each bio page

### ISSUE THREAD

**Issue by kholuba** [elotroalex/frontlines#1]
The name of each nurse on their bio page cuts in to the line below.

**Comment by elotroalex** [comment]
Not sure what this described, but these pages seem to be responsive now.

**Comment by kholuba** [comment]
The original issue I was talking about seems to be fixed. For example, on Margaret Loma Phiri's page, the "g" in her name covered up part of her title beneath her name. But that looks good now.

However, I think that the picture for each nurse should be moved down a few spaces. For example, look at the page for Patience D. Cooper Tokpah. Her name takes up 2 lines and pushes her title over her face. On other pages (with shorter last names) I think the title is kind of covered or obscured by the picture. I think it would look cleaner if there was some blue in between the title and the picture on every nurse's page.

**Comment by elotroalex** [comment]
Hi Kurt,

None of the changes I'm making are online yet. You will be able to see them
tomorrow probably. I'll let you know.

**Comment by elotroalex** [comment]
(Including the issue with the pictures, which is fixed already)

**Comment by kholuba** [comment]
The titles for many of the nurses (see Annette Mwansa Nwokane, many others) cuts into the nurse's picture. Can you please move the picture further down the page so there is no overlap?

**Comment by elotroalex** [comment]
I'll need a picture for this. I can't recreate it here.

**Comment by kholuba** [comment]
![NursePageScreenshot](https://user-images.githubusercontent.com/67760672/102546569-da2ad400-4085-11eb-8cee-12a110e3d716.jpg)

**Comment by elotroalex** [comment]
is this after hard refresh?

**Comment by kholuba** [comment]
Yes

**Comment by elotroalex** [comment]
fixed
