### ISSUE TITLE
iPad Viewing Bugs

### ISSUE THREAD

**Issue by kholuba** [elotroalex/frontlines#12]
- Ebola landing page: The block of text gets smushed down to the bottom left. Hard to describe but format is off.

- Ebola Timeline page: "Timeline" at the top is cut off into two lines

- Ebola History page: "History" at the top is cut off into two lines

- Homepage: "Frontline Nurses" logo is cut off into 3 lines

**Comment by elotroalex** [comment]
Most of these should be fixed, but we should re-test closer to the launch date as more fixes and last minute changes come in.

**Comment by elotroalex** [comment]
just pushed a copy to the dev site so you can test this asap. let me know if there are still issues on ipad.

**Comment by kholuba** [comment]
-

**Comment by elotroalex** [comment]
Let's leave it open until we got it all more or less passable.

**Comment by elotroalex** [comment]
now we're good.
