### ISSUE TITLE
Remove Malawi sort function in nurses profiles

### ISSUE THREAD

**Issue by minagshah** [elotroalex/frontlines#14]
Margaret Loma Phiri is from Malawi, but worked in Sierra Leone during the Ebola outbreak. I think we should remove the "Malawi" sort function at the top of the nurses' profiles landing page and group Dr. Phiri with the other nurses from Sierra Leone to avoid confusion.

**Comment by elotroalex** [comment]
did you make this change in the spreadsheet? these buttons are automatically generated based on the country categories in the spreadsheet.

**Comment by minagshah** [comment]
Made the change in the spreadsheet; also added an issue about the fact I made those changes!
