### ISSUE TITLE
About Page Picture Addition

### ISSUE THREAD

**Issue by kholuba** [elotroalex/frontlines#15]
Please add the image titled "about-a.jpg" to the About Page directly below paragraph 6

**Comment by minagshah** [comment]
Please add image titled "about-page-c.jpg" to the About page directly below paragraph 1, "about-page-d.jpg" below paragraph 2, and "about-page-b.jpg" below paragraph 4.

**Comment by elotroalex** [comment]
let's try these images with captions. can you provide those?

**Comment by minagshah** [comment]
Yes! And actually, Victoria only wants us to use one of those pictures, so let's keep "about-page-c.jpg" and disregard my comments about the others. I've deleted them from the pictures file. 

The caption for that photo should read: "From left to right, Mwansa Nkowane, Senesie Margao, Jennifer Dohrn, Mary Fullah, Susan Michaels-Strasser, Joan Shepard, Jeremy Orloff, Margaret Phiri, Freetown, Sierra Leone, summer 2019."

**Comment by elotroalex** [comment]
cool
