### ISSUE TITLE
Nurses bio on each page

### ISSUE THREAD

**Issue by kholuba** [elotroalex/frontlines#2]
The bio for each nurse is below the transcript and hard to see. I think it should be above the SoundCloud player at the top of the bio page for each nurse.

**Comment by elotroalex** [comment]
I kinda like it in the bottom, but at the end of the day, as long as it doesn't come in between the sound and the transcription, I could be persuaded.

**Comment by kholuba** [comment]
Mina and I agreed that it would be best if we could put it above the Soundcloud bar. We think that it allows the viewer to understand what they are listening to better if they can read who the person is first.
