### ISSUE TITLE
n02 soundcloud stream not coming in

### ISSUE THREAD

**Issue by elotroalex** [elotroalex/frontlines#22]
at least on my computer

**Comment by elotroalex** [comment]
might not be a bad idea to go over each one to see if any others are not coming in either.

**Comment by kholuba** [comment]
We had an issue with n02 a while ago. I fixed n02 (Darboi Korkoyah) in Issue #5, which you closed. The HTML embed code is 879344959

The audio in SoundCloud is good

Is there something else I should do?

**Comment by kholuba** [comment]
All other audio works for every other nurse

**Comment by elotroalex** [comment]
Looks like the old number made it back into the data. I'll add this number
to the data on my end. Can you make sure that number is in the data on your
end?

**Comment by kholuba** [comment]
Yea it should be all good. That's the number from SoundCloud and I have it in the shared GoogleSheet "Sound Cloud Links for Interview Audio Clips"
