### ISSUE TITLE
Add Reflections Section/Page

### ISSUE THREAD

**Issue by kholuba** [elotroalex/frontlines#24]
I'm not sure how we want to do this- add another page/section on the Ebola frontpage? Or insert it into the About page? I'm fine with whatever you think is best.

We are still waiting on the reflection paragraph from Susan. She is the only one we're missing and I just sent her a reminder email. I attached a word doc with everyone else's reflections to this issue.

[Self-Reflections from Team.docx](https://github.com/elotroalex/frontlines/files/5710924/Self-Reflections.from.Team.docx)

**Comment by elotroalex** [comment]
We should discuss this on Friday.
