### ISSUE TITLE
History page Cleanup

### ISSUE THREAD

**Issue by kholuba** [elotroalex/frontlines#25]
1. Can you please center the pictures instead of the left-side allignment?

2. Also, could you make the caption a different color or much smaller font. And add a space between the caption and the next paragraph below. It seems to all blend together and needs to be separated.

3. This one is not as essential, but would it be possible to add numbers to the Notes at the bottom of the page? I know that when you click the in-text reference number it takes you to the correct Note at the bottom, but it would look nicer and be easier to navigate if the Notes at the bottom were numbered according to their placement in the document text.

**Comment by elotroalex** [comment]
No clue why the numbers are not showing up on the bottom. I'll look into it. 

I'll justify the images. Probably better. The captions are already a different color and smaller. What are you talking about? Paste a picture below.

**Comment by kholuba** [comment]
![HistoryPageScreenshot](https://user-images.githubusercontent.com/67760672/102546280-65f03080-4085-11eb-8572-9e3293cabe12.jpg)

**Comment by elotroalex** [comment]
That is indeed weird. Here's how it looks like on mine:

[image: Screen Shot 2020-12-17 at 4.33.29 PM.png]

**Comment by elotroalex** [comment]
Try to hard refresh. Search for "hard refresh ipad" and the name of your
browser for instructions

**Comment by kholuba** [comment]
Yes, hard refresh worked. Captions look good. Notes at the bottom still don't look good.

**Comment by elotroalex** [comment]
Yeah, the notes at the bottoms is a weird bug. I'll work on it next week probably.

**Comment by elotroalex** [comment]
all good
