### ISSUE TITLE
Menu Pop-Out

### ISSUE THREAD

**Issue by kholuba** [elotroalex/frontlines#26]
When you are on a nurse profile page (go to Patience T. Cooper Kokpah), and you click on the menu in the top right corner, the pop-out menu is behind the name of the nurse. Then, you can't click on the menu items. Is there a way to make the menu in front of everything always?

**Comment by elotroalex** [comment]
That one I fixed already. Looks like you need to hard refresh your pages.
Do you know how to hard refresh? This might also explain why some older
changes are not reflecting on your end too. Might.

**Comment by elotroalex** [comment]
Check here too @kholuba

**Comment by kholuba** [comment]
Yes. Working now. Sorry about all these!
