### ISSUE TITLE
About page title

### ISSUE THREAD

**Issue by kholuba** [elotroalex/frontlines#27]
The title on the About page is overlapping with the text

**Comment by elotroalex** [comment]
No clue what you mean.

**Comment by kholuba** [comment]
![AboutPageTitle](https://user-images.githubusercontent.com/67760672/102546442-a5b71800-4085-11eb-9910-a006517a1aa2.jpg)

**Comment by elotroalex** [comment]
Let me know after you've hard refreshed

**Comment by kholuba** [comment]
All good! It's fixed. Just needed to hard refresh
